"""Add about and last seen

Revision ID: 878fcd550607
Revises: 93c582301614
Create Date: 2023-11-09 16:25:43.916578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '878fcd550607'
down_revision = '93c582301614'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
